# This file contains values from Cookiecutter

default_context:
  project_name: "eyes3scribe"
  project_description: "Automatically creates HTML documentation files for BASH/Shell source code using markdown & python mkdocs"
  organization: "Stablecaps"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.9
  github_name: "stablecaps"
  email: "14529342+darkpandarts@users.noreply.github.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
