---
project_name: docs_stablecaps_bashrc
site_name: stablecaps bashrc
site_url: https://github.com/stablecaps/stablecaps.github.io
site_author: giri
repo_url: https://github.com/stablecaps/stablecaps_bashrc/
shell_srcdir: /home/bsgt/stablecaps_bashrc
shell_glob_patterns:
  - "*.bash"
  - "*.sh"
exclude_patterns:
  - "zsdoc"
  - "test"
  - "theme_settings_BACKUP"
additional_mdfiles:
  /home/bsgt/stablecaps_bashrc/README.md: index.md
category_names_src:
  - aliases
  - completion
  - modules
  - internal
