---
### conf mkdocs
project_name: docs_bash-it
site_name: bash-it
site_url: https://github.com/Bash-it/bash-it.github.io
site_author: giri
repo_url: https://github.com/Bash-it/bash-it/
theme:
  name: windmill-dark
  navigation_depth: 5
  highlightjs: true
  hljs_languages:
  - bash
  - python
extra_css:
  - custom_css/extra.css
nav:
- Home: index.md

### conf bashautodoc
nav_codedocs_as_ref_or_main: ref
nav_codedocs_name: Reference
shell_srcdir: /media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/bash-it
shell_glob_patterns:
  - "*.bash"
  - "*.sh"
exclusion_patterns_src:
  - docs/docs
  - hooks
  - lib
  - test
  - test_lib
  - themes
  - _build
  - Thumbs.db
  - .DS_Store
  - venv
category_names_src:
  - aliases
  - completion
  - plugins
#
handwritten_docs_dir: /media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/bash-it/docs
docs_glob_patterns:
  - "*.md"
  - "*.rst"
exclusion_patterns_docs:
  - docs/docs
  - LICENSE
  - _build
  - Thumbs.db
  - .DS_Store
  - venv
category_names_docs:
  - commands
  - themes-list
  - ./
additional_mdfiles:
  /media/bsgt/jogi1/XX_local_PSYNC_linux2/XXX_CONTRACTING/stablecaps/0000_STABLECAPS_GITREPOS/bash-it/docs/README.md: index.md
