nav:
- Home: index.md
- aliases
- completion
- modules
- internal
repo_url: https://github.com/stablecaps/stablecaps_bashrc/
site_author: giri
site_name: sys bashrc
site_url: https://github.com/stablecaps/stablecaps.github.io
